//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class twitch10dblocalhostEntities1 : DbContext
    {
        public twitch10dblocalhostEntities1()
            : base("name=twitch10dblocalhostEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Build> Build { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserHasBuild> UserHasBuild { get; set; }
    }
}
