// <auto-generated />
namespace Twitch10WcfService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170731 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170731));
        
        string IMigrationMetadata.Id
        {
            get { return "201707302220196_2017-07-31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
